### ISSUE TITLE
is there anyway i can download all config 

### ISSUE THREAD

**Issue by teamsmiley** [fortinet-ansible-dev/ansible-galaxy-fortiswitch-collection#1]
is there anyway i can download all config

**Comment by JieX19** [comment]
Hi @teamsmiley 

Sure. We have a module called 'backup full config' to download all configs at once.  

This is the FAQ link in which you can find examples for this module. https://ansible-galaxy-fortiswitch-docs.readthedocs.io/en/galaxy-1.1.0/faq.html

I hope this helps, but let me know if you have any questions.

**Comment by teamsmiley** [comment]
ERROR! couldn't resolve module/action 'fortiswitch_execute_backup_default_config'. This often indicates a misspelling, missing collection, or incorrect module path.

i get this error . i installed collection already 

do you have any idea?

**Comment by teamsmiley** [comment]
oh 1.1.0 work. but i dont get any output.

**Comment by teamsmiley** [comment]
```
- name: "Backup Switch's Full Configuration"
      fortiswitch_execute_backup_full_config:
        enable_log: yes
        execute_backup_full_config:
          config: default

    - name: "default config backup"
      fortiswitch_execute_backup_default_config:
        enable_log: yes
        execute_backup_default_config:
          config: test
```
