### ISSUE TITLE
Setting ssh keys for admin user.

### ISSUE THREAD

**Issue by TafkaMax** [fortinet-ansible-dev/ansible-galaxy-fortiswitch-collection#7]
I am having an issue where I can't add ssh-keys to user via `fortiswitch_system_admin`

```
 FAILED! => {"changed": false, "meta": {"build": 453, "cmdb-checksum": "5045064375657548524", "cmdb-index": "750", "error_reason": "Invalid SSH public key.\n", "http_method": "POST", "http_status": 400, "name": "admin", "path": "system", "serial": "REDACTED", "status": "error", "timestamp": "2023-12-22T14:09:57Z", "vdom": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "version": "v7.2.5"}, "msg": "Error in repo"}
```

The code is the following:

```
- name: Register 'read-only-admin' user if not present in vdom 'root'.
  fortinet.fortiswitch.fortiswitch_system_admin:
    state: present
    system_admin:
      name: 'read-only-admin'
      accprofile: 'read-only-profile'
      comments: "Read Only privileged admin user to save backup configuration."
      password: '{{ switch_ro_password }}'
      ssh_public_key1: "{{ lookup('file', '{{ playbook_dir }}/files/ssh_pubkeys/oxidized_id_rsa.pub' ) }}"
      vdom: 'root'
      force_password_change: disable
```

The output of the lookup is OK aswell. "ssh-rsa AA....== comment"
