### ISSUE TITLE
could not use all.ini in group var to replace the var value in inventory file

### ISSUE THREAD

**Issue by HaroldYE** [fortinet-ansible-dev/ansible-galaxy-fortiswitch-collection#8]
I am trying to use group _vars/all.ini

and put  the most of the var into it

[fsw_switches:vars]
ansible_network_os=fortinet.fortiswitch.fortiswitch
ansible_user=""
ansible_password=""
ansible_httpapi_use_ssl=true
ansible_httpapi_validate_certs=false
ansible_httpapi_port="443"
ansible_connection="httpapi"
ansible_collections="fortinet.fortiswitch"

but when i run 

ansible-playbook -i inventory.ini playbooks.yml, it ask me to get ssh login and after it show model has not been define in task

ERROR! couldn't resolve module/action 'fortinet.fortiswitch.fortiswitch_switch_auto_network'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in fsw_srv_core.yaml': line 8, column 11, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:

my inventory file looks like

[fsw_switches:children]
fsw_srv_core
fsw_sto_core

[fsw_srv_core]
c1 ansible_host=10.76.0.245
c2 ansible_host=10.76.0.246

[fsw_sto_core]
cs1 ansible_host=10.76.0.247
cs2 ansible_host=10.76.0.248

it works when I have var define in inventory file but fail when I separate it, seem it does not take the all.ini become var

wondering is anyway we can have all.ini as a seperate var from inventory file?

**Comment by MaxxLiu22** [comment]
Hi @HaroldYE ,

Thank you for your question. We can define these variables in a JSON file and refer to it in the task as shown. Please let me know if this solution does not fully meet your needs or if you have any further questions.

fortiswitch_system_admin.yml
```
- hosts: fortiswitch01
  collections:
    - fortinet.fortiswitch
  connection: httpapi
  vars_files:
    - group_vars/all.ini
  tasks:
  - name: Register 'read-only-admin' user if not present in vdom 'root'.
    fortinet.fortiswitch.fortiswitch_system_admin:
      state: present
      system_admin:
        name: 'prof-admin'
        accprofile: 'prof_admin'
        comments: "Read Only privileged admin user to save backup configuration."
        password: 'ansible_Swe'
        ssh_public_key1: "{{ lookup( 'file', 'key.txt') | string  }}"
        vdom: 'root'
        force_password_change: disable
```
group_vars/all.json
```
{
    "ansible_network_os": "fortinet.fortiswitch.fortiswitch",
    "ansible_user": "usr",
    "ansible_password": "psw",
    "ansible_httpapi_use_ssl": true,
    "ansible_httpapi_validate_certs": false,
    "ansible_httpapi_port": "443",
    "ansible_connection": "httpapi",
    "ansible_collections": "fortinet.fortiswitch"
}
```

Thanks,
Maxx
